sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
  - cd Api
  - echo "Work folder set up"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  deploy:
    provider: script
    script:
      docker tag api:latest $DOCKER_USERNAME/rest-api:$TRAVIS_JOB_ID;
      docker tag api-db:latest $DOCKER_USERNAME/rest-api-db:$TRAVIS_JOB_ID;
      docker push $DOCKER_USERNAME/rest-api:$TRAVIS_JOB_ID;
      docker push $DOCKER_USERNAME/rest-api-db:$TRAVIS_JOB_ID;
    on:
      branch: main
notifications:
  email: false
