CREATE TABLE IF NOT EXISTS USERS(
    ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(400) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    DISPLAYNAME VARCHAR(255) NOT NULL,
    CREATED DATETIME DEFAULT CURRENT_TIMESTAMP
);