version: "3.4"

services:
  db:
    image: api-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: api
    ports:
      - 3308:3306
    networks:
      - api-network
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44399:80
    depends_on:
      - db
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
